batch_size: 8
epochs: 11
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 50
weight_decay: 10e-6
fp16_precision: False

model:
  out_dim: 256
  base_model: "resnet18"

dataset:
  s: 1
  input_shape: (512,512,3)
  num_workers: 0
  valid_size: 0.4

loss:
  temperature: 0.5
  use_cosine_similarity: True
